server {
    listen 80;
    server_name localhost;

    # Фронтенд
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Auth Service API
    location /api/auth/ {
        # rewrite ^/api/auth/(.*)$ /auth/$1 break; # бесячая штука (annoying thing)
        proxy_pass http://auth-service:8081/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_redirect off;
    }


    # Задел на будущее 
    # location /api/roadmap/ {
    #     rewrite ^/api/roadmap/(.*)$ /$1 break; 
    #     proxy_pass http://roadmap-service:8082;
    # }

    # # Пример для Solver-service
    # location /api/solver/ {
    #     rewrite ^/api/solver/(.*)$ /$1 break;
    #     proxy_pass http://solver-service:8083;
    # }

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
