spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_ROADMAP_DB_HOST}:${POSTGRES_ROADMAP_DB_INTERNAL_PORT}/${POSTGRES_ROADMAP_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - debug
          - env

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG

server:
  port: ${ROADMAP_HTTP}

jwt:
  access-token:
    lifetime: ${ACCESS_TOKEN_LIFETIME}
  refresh-token:
    lifetime: ${REFRESH_TOKEN_LIFETIME}
  secret: ${JWT_SECRET}

CODE_PATTERN: ${ACTUAL_CODE_PATTERN}

springdoc:
  swagger-ui:
    path: /solver/swagger-ui.html
  api-docs:
    path: /solver/v3/api-docs

SWAGGER_API_VERSION_SOLVER: ${ENV_SWAGGER_API_VERSION_SOLVER}
SWAGGER_APP_DESCRIPTION_SOLVER: ${ENV_SWAGGER_APP_DESCRIPTION_SOLVER}
SWAGGER_LICENSE: ${ENV_SWAGGER_LICENSE}
SWAGGER_LICENSE_URL: ${ENV_SWAGGER_LICENSE_URL}
SWAGGER_DEV_SERVER_SOLVER: ${ENV_SWAGGER_DEV_SERVER_SOLVER}
